/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_Pins.h"
#include "CapSense_TunerHelper.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "Pin_2.h"
#include "Pin_2_aliases.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "CapSense_IntClock.h"
#include "CapSense_CompCH0.h"
#include "CapSense_AMuxCH0.h"
#include "CapSense_IdacCH0.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "PSoC3_8051.h"
#include "cy_em_eeprom.h"

/*[]*/

